import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { create, deleteMember, getAllMembers, getSinglemember, update } from './memberApi';

export const fetchAllMembers = createAsyncThunk(
  'member/allMembers',
  async ({ page , centerId}) => {
    const response = await getAllMembers({ page ,centerId });
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchSingleMember = createAsyncThunk(
  'member/singleMember',
  async ({ id }) => {
    const response = await getSinglemember({ id });
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);


export const fetchCreateMember = createAsyncThunk(
  'member/create',
  async ({ mData }) => {
    const response = await create({ mData});
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchUpdateMember = createAsyncThunk(
  'member/update',
  async ({ mData }) => {
    const response = await update({ mData});
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchDeleteMember = createAsyncThunk(
  'member/delete',
  async ({ Id }) => {
    const response = await deleteMember({Id});
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);



export const memberSlice = createSlice({
  name: 'member',
  initialState:{
    value: 0,
    members:[],
    currentPage: 1,
    totalPages: 1,
    totalRecords: 0,
    loading: false,
    isMemberCreate:null,
    singleMember:null,
    member:null,
    emis:[],
    isSubmitting:false
  },
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
   setAuthFromStorage: (state, action) => {
      state.token = action.payload.token;
      state.isAuthenticated = true;
    },
    setUpdateStatus: (state, action) => {
      state.isMemberCreate = null;
    },
    setCurrentPage: (state, action) => {
      state.currentPage = action.payload;
    },
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
     
      .addCase(fetchAllMembers.pending, (state) => {
         state.loading = true;
         state.totalRecords = 'Processing...';    
      })
      .addCase(fetchAllMembers.fulfilled, (state, action) => {
          state.loading = false;
          state.members = action.payload.data.members;
          state.currentPage = action.payload.data.pagination.current_page;
        state.totalPages = action.payload.data.pagination.last_page;
        state.totalRecords = action.payload.data.pagination.total;
      }).addCase(fetchAllMembers.rejected, (state ,action) => { 
          state.loading = false;
          state.totalRecords = action.error.message;
      })
      
      .addCase(fetchCreateMember.pending, (state) => {
        state.isMemberCreate = 'pending';
        state.isSubmitting = true;
      })
      .addCase(fetchCreateMember.fulfilled, (state, action) => {
          state.isMemberCreate = 'create';
          state.isSubmitting = false;
      }).addCase(fetchCreateMember.rejected, (state ,action) => {
        state.isMemberCreate = 'error';
      })
      
       .addCase(fetchUpdateMember.pending, (state) => {
        state.isMemberCreate = 'pending';
        state.isSubmitting = true;
      })
      .addCase(fetchUpdateMember.fulfilled, (state, action) => {
          state.isMemberCreate = 'update';
          state.isSubmitting = false;
      }).addCase(fetchUpdateMember.rejected, (state ,action) => {
        state.isMemberCreate = 'error';
      })
      
      .addCase(fetchDeleteMember.pending, (state) => {
        state.isMemberCreate = 'pending';
      })
      .addCase(fetchDeleteMember.fulfilled, (state, action) => {
          state.isMemberCreate = 'delete';
      }).addCase(fetchDeleteMember.rejected, (state ,action) => {
        state.isMemberCreate = 'error';
      })

       .addCase(fetchSingleMember.pending, (state) => {
        state.loading = true;
      })
      .addCase(fetchSingleMember.fulfilled, (state, action) => {
          state.member = action.payload.data.member;
          state.emis = action.payload.data.member.emis;
          state.loading = false;
      }).addCase(fetchSingleMember.rejected, (state ,action) => {
          state.loading = true;
      })
      
    
      ;
      
  },
});

export const { setAuthFromStorage , setUpdateStatus , setCurrentPage} = memberSlice.actions;


export default memberSlice.reducer;
