import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { getDashboardData, update } from './emisApi';

export const fetchUpdateEmi = createAsyncThunk(
  'emi/update',
  async ({ emiData }) => {
    const response = await update({ emiData});
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchDashboardData = createAsyncThunk(
  'dashboard/getDashdata',
  async ({ filterData }) => {
    const response = await getDashboardData({ filterData});
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);



export const emiSlice = createSlice({
  name: 'emis',
  initialState:{
    value: 0,
    isEmiUpdated:null,
    dashBoardData:[],
    fetchingdata:false
  },
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
   setAuthFromStorage: (state, action) => {
      state.token = action.payload.token;
      state.isAuthenticated = true;
    },
    setEmiUpdated: (state, action) => {
      state.isEmiUpdated = null;
    },
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchUpdateEmi.pending, (state) => {
        state.isEmiUpdated = null;
      })
      .addCase(fetchUpdateEmi.fulfilled, (state, action) => {
          state.isEmiUpdated = "updated";
      }).addCase(fetchUpdateEmi.rejected, (state ,action) => {
        state.isEmiUpdated = "error";
      })

      .addCase(fetchDashboardData.pending, (state) => {
        state.fetchingdata = false;
      })
      .addCase(fetchDashboardData.fulfilled, (state, action) => {
          state.fetchingdata = true;
          state.dashBoardData = action.payload.data;
      }).addCase(fetchDashboardData.rejected, (state ,action) => {
          state.fetchingdata = false;
      })
      ;
      
  },
});

export const { setAuthFromStorage , setUpdateStatus , setEmiUpdated} = emiSlice.actions;


export default emiSlice.reducer;
