import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { create, deleteRole, getAllRoles, update } from './rolesApi';


export const fetchAllRoles = createAsyncThunk(
  'role/allRoles',
  async ({ token, page}) => {
    const response = await getAllRoles({ token, page });
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);


export const fetchCreateRole = createAsyncThunk(
  'role/create',
  async ({ token,roleData }) => {
    const response = await create({token , roleData});
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchUpdateRole = createAsyncThunk(
  'role/update',
  async ({ token,roleData }) => {
    const response = await update({token , roleData});
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fetchDeleteRole = createAsyncThunk(
  'role/delete',
  async ({ token,Id }) => {
    const response = await deleteRole({token , Id});
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);


export const roleSlice = createSlice({
  name: 'roles',
  initialState:{
    roles:[],
    currentPage: 1,
    totalPages: 1,
    totalRecords: 0,
    loading: false,
    isRoleCreate:null
  },
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
   setAuthFromStorage: (state, action) => {
      state.token = action.payload.token;
      state.isAuthenticated = true;
    },
    setUpdateStatus: (state, action) => {
      state.isRoleCreate = null;
    },
    setCurrentPage: (state, action) => {
      state.currentPage = action.payload;
    },
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
    
      .addCase(fetchAllRoles.pending, (state) => {
         state.loading = true;       
      })
      .addCase(fetchAllRoles.fulfilled, (state, action) => {
          state.loading = false;
          state.roles = action.payload.data.roles;
          state.currentPage = action.payload.data.pagination.current_page;
        state.totalPages = action.payload.data.pagination.last_page;
        state.totalRecords = action.payload.data.pagination.total;
      }).addCase(fetchAllRoles.rejected, (state ,action) => { 
          state.loading = false;
      })
      
      .addCase(fetchCreateRole.pending, (state) => {
        state.isRoleCreate = 'pending';
      })
      .addCase(fetchCreateRole.fulfilled, (state, action) => {
          state.isRoleCreate = 'create';
      }).addCase(fetchCreateRole.rejected, (state ,action) => {
        state.isRoleCreate = 'error';
      })
      
       .addCase(fetchUpdateRole.pending, (state) => {
        state.isRoleCreate = 'pending';
      })
      .addCase(fetchUpdateRole.fulfilled, (state, action) => {
          state.isRoleCreate = 'update';
      }).addCase(fetchUpdateRole.rejected, (state ,action) => {
        state.isRoleCreate = 'error';
      })
      
      .addCase(fetchDeleteRole.pending, (state) => {
        state.isRoleCreate = 'pending';
      })
      .addCase(fetchDeleteRole.fulfilled, (state, action) => {
          state.isRoleCreate = 'delete';
      }).addCase(fetchDeleteRole.rejected, (state ,action) => {
        state.isRoleCreate = 'error';
      })
      ;
      
  },
});

export const { setAuthFromStorage , setUpdateStatus , setCurrentPage} = roleSlice.actions;


export default roleSlice.reducer;
